import requests
s=requests.session()
print("==================================登录前的cookie",s.cookies)
url="https://bagevent.com/user/login"
user={
    "access_type":"1",
    "loginType":'1',
    "emailLoginWay":'0',
    "account":"2780487875@qq.com",
    "password":'qq2780487875',
    "remindmeBox":"on",
    "remindme":'1'
}
r=s.post(url,data=user)
print(r.text)
print("==================================登录后的cookie",s.cookies)
#获取账户的信息
url="https://www.bagevent.com/account/dashboard"
r=s.get(url)
print(r.text)
print("++++++++++++++++++++++++++++++++++++++++")
url="https://www.bagevent.com/user/login_out"
r=s.get(url)
print(r.text)
print("+++++++++++++++++++++++++++++++退出后的cookie",s.cookies)
